### ISSUE TITLE
Netlink socket bind error when starting qutebrowser with flatpak run

### ISSUE THREAD

**Issue by tinywrkb** [flathub/org.qutebrowser.qutebrowser#19]
**edit: This seems to be a generic issue with Chromium-based browsers**

When starting the app from the command-line like this
```
flatpak run org.qutebrowser.qutebrowser
```
or
```
flatpak run  --command=sh org.qutebrowser.qutebrowser -c /app/bin/qutebrowser
```
I'm getting the following error message
```
[2:25:0320/192253.351158:ERROR:address_tracker_linux.cc(201)] Could not bind NETLINK socket: Address already in use (98)
```

Here's the relevant strace output
```
[pid 40150] bind(58, {sa_family=AF_NETLINK, nl_pid=2, nl_groups=0x000113}, 12 <unfinished ...>
...
[pid 40150] <... bind resumed>)         = -1 EADDRINUSE (Address already in use)
...
[pid 40150] write(2, "[2:21:0320/182848.620724:ERROR:a"..., 121 <unfinished ...>
[2:21:0320/182848.620724:ERROR:address_tracker_linux.cc(201)] Could not bind NETLINK socket: Address already in use (98)
```
Full strace output: [strace_flatpak_run_exec.log](https://github.com/flathub/org.qutebrowser.qutebrowser/files/6176075/strace_flatpak_run_exec.log)

But if I start qutebrowser from the sandbox like this
```
# enter the sandbox
flatpak run  --command=sh org.qutebrowser.qutebrowser
# run the app
/app/bin/qutebrowser
```
then I don't have such an error.  
And the strace output
```
[pid    30] bind(62, {sa_family=AF_NETLINK, nl_pid=6, nl_groups=0x000113}, 12 <unfinished ...>
...
[pid    30] <... bind resumed>)         = 0

```
Full strace output: [strace_inside_sandbox_exec.log](https://github.com/flathub/org.qutebrowser.qutebrowser/files/6176077/strace_inside_sandbox_exec.log)

In both cases, this is the first bind call for a netlink socket.

**Comment by danieldg** [comment]
from man 7 netlink: "If the application sets nl_pid before calling bind(2), then it is up to the application to make sure that nl_pid is unique."  At a guess, 2 is not unique but 6 is.  This likely needs to be changed in chromium; using 0 for nl_pid (requesting the kernel assign it) would suffice.

**Comment by tinywrkb** [comment]
If this doesn't have ill effects then we can close this issue.

**Comment by tinywrkb** [comment]
This is an upstream bug.

**Comment by dmcardle** [comment]
FYI, the upstream bug should be fixed now. See https://crbug.com/1224428.

**Comment by tinywrkb** [comment]
@dmcardle thanks for the update.  

I'm guessing that it might take a while for the fix to reach this app. The latest version of QtWebEngine 5.xx.x is 5.15.5, and it's using Chromium 87.0.4280.144.  
Maybe we would even need to wait for qutebrowser to switch to PyQt 6.
