### ISSUE TITLE
Cannot execute Gvim or MPV from within Qutebrowser

### ISSUE THREAD

**Issue by jconnolly837** [flathub/org.qutebrowser.qutebrowser#221]
OpenSUSE 15.4, all mentioned apps are from flathub and installed as system apps

Steps taken to try to allow these apps to be launched from Qutebrowser: 
`sudo flatpak override --talk-name=org.freedesktop.Flatpak org.qutebrowser.qutebrowser`
`mkdir -p ~/.var/app/org.qutebrowser.qutebrowser/data/bin`
`ln -s /app/lib/flatpak-spawn-wrapper/wrapper ~/.var/app/org.qutebrowser.qutebrowser/data/bin/gvim`
All completed seemingly successfully without error, or any output at all. All apps have been closed and opened since doing this process. That directory and symlink exist as they should as far as I can tell. 

I also tried granting `org.gvim.Gvim` and `io.mpv.Mpv` `--talk-name=org.freedesktop.Flatpak`, but with no success within Qutebrowser. I don't know enough about this to know if that really did anything helpful. 

### MPV opening the COSTA RICA video with the snake thumbnail
![mpv](https://user-images.githubusercontent.com/26425730/175755860-64a486dd-08e1-45b5-a74c-d139ddb19494.png)
<h2 style="font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Info</h2>

Command | mpv 'https://www.youtube.com/watch?v=LXb3EKWsInQ'
-- | --
Status | Command exited with status 2.

<h2 style="font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Standard output</h2><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> (+) Video --vid=1 (*) (vp9 1920x1080 59.940fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: Jacob + Katie Schwarz
 Channel_URL: https://www.youtube.com/channel/UCYq-iAOSZBvoUxvfzwKIZWA
[vo/gpu] Can't open TTY for VT control: No such device or address
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] Failed to set CRTC for connector 56: Permission denied
[vo/sdl] SDL_Init failed
Error opening/initializing the selected video_out (--vo) device.
Video: no video

Exiting... (Errors when loading file)
</pre><h2 style="font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Standard error</h2><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Invalid MIT-MAGIC-COOKIE-1 keyradeon: Failed to get PCI ID, error number -13
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key</pre>

### GVIM trying to edit the Youtube search page URL
![gvim](https://user-images.githubusercontent.com/26425730/175755883-5fb59014-1b86-4b14-8004-700717244bfc.png)
<header style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="color: rgb(68, 68, 68); font-weight: normal;">Process 497: gvim</h1></header><h2 style="font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Info</h2>

Command | gvim -f /tmp/qutebrowser-editor-o3657al6 -c 'normal 1G0l'
-- | --
Status | Editor exited with status 1.

<h2 style="font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Standard output</h2><span style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 254, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">No output.</span><h2 style="font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Standard error</h2><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">flatpak-spawn-wrapper: Couldn't found a host executable 'gvim' or suitable Flatpak app</pre>

### END
Gvim and MPV work properly on their own. 

I successfully did this with flatpak apps installed as user on a Debian 11 system from instruction in [this Reddit thread](https://old.reddit.com/r/flatpak/comments/vchjua/how_do_i_make_a_program_executable_inside_a/icgw1a2/). If you think it would matter at all, I can reinstall all three apps as user and test them. 

I'll provide any more information that I can upon request.

**Comment by tinywrkb** [comment]
I'll have to look at this a bit later, I hope that's alright.

**Comment by jconnolly837** [comment]
> I'll have to look at this a bit later, I hope that's alright.

Yes that's alright. 

I was going to comment here earlier tonight that MPV randomly started working for no apparent reason, and that Gvim remains broken. I've been working on Gvim and it appears that Qutebrowser is not writting the file it says it is to /tmp, even when I give both apps rw access. 

I'm working on other unrelated computery problems which is why I didn't get to this until you commented. I may continue playing with Gvim soon or much much later, idk when.

**Comment by tinywrkb** [comment]
The mpv error is likely due to missing environment variables in the systemd user session environment.  
You should have at least `DISPLAY` or `WAYLAND_DISPLAY` set, and should be set before `flatpak-session-helper.service` is started, or restart the service after updating the environment.  

- You can check the system user environment with `$ systemctl --user show-environment`.
- You can set environment variables with `$ systemctl --user set-environment VAR=VALUE ...`.
- You can import environment variables from the current environment to system user environment with `$ systemctl --user import-environment VAR ...`.

For example, I have the following in my Sway config file:

```
exec systemctl --user import-environment DISPLAY SWAYSOCK WAYLAND_DISPLAY XAUTHORITY XDG_SESSION_TYPE
exec hash dbus-update-activation-environment 2>/dev/null && \
  dbus-update-activation-environment --systemd DISPLAY SWAYSOCK WAYLAND_DISPLAY XAUTHORITY XDG_SESSION_TYPE
```

Both `io.mpv.Mpv` and `io.github.celluloid_player.Celluloid` are working for me. They both supported by the bundled flatpak-spawn wrapper, so no need to create symlinks, though there's a way to get better startup time, which will be mentioned in the wiki soon.

**Comment by jconnolly837** [comment]
One more thing. I had to create a script in $PATH to run the flatpak Gvim, otherwise Qutebrowser simply can't find Gvim. That's why it said `flatpak-spawn-wrapper: Couldn't found a host executable 'gvim' or suitable Flatpak app`. Once that was done, I'm running into the issue I have now, which is Gvim is not taking the input because Qutebrowser is not putting a file with the URL in /tmp. There may be more issues down the line. 
![Screenshot_20220626_133748](https://user-images.githubusercontent.com/26425730/175829267-8819bf91-bcdf-4624-884b-dd3d7a13c44f.png)

**Comment by tinywrkb** [comment]
Did you add filesystem=/tmp override permission for both apps?

**Comment by jconnolly837** [comment]
> Did you add filesystem=/tmp override permission for both apps?

Yes, it's been set for the past day or two. 

Another update. Qutebrowser has decided to start writting to /tmp and Gvim half works. It seems Gvim is opening the file twice. If I press Enter to dismiss the error, make my edit, ZZ, then ZZ again to take care of the 2nd instance, the URL change gets passed to Qutebrowser and it loads that URL as intended. I'll keep playing with it to figure out why it's opening the tmp file twice. 

At this point, it feels like I'm fixing this thing with hopes and dreams and crossed fingers.

**Comment by jconnolly837** [comment]
It seems the double opening issue gets fixed if I set `editor.command` to `'["gvim", "-f", "{file}"]'` in Qutebrowser. By default, it's `'["gvim", "-f", "{file}", "-c", "normal {line}G{column0}l"]'`. 

So at the moment, it appears that I now have a fully functioning Qutebrowser setup. 

### Summary
**MPV:** Started working by itself for seemingly no reason. 

**Gvim:** Both Qutebrowser and Gvim require rw access to /tmp. Gvim needs to have an executable in $PATH. I put one in /usr/bin/ containing `flatpak run org.vim.Vim -g $@` along with a shebang to /usr/bin/sh.

**Comment by tinywrkb** [comment]
I just sent a PR that adds gvim symlink and the Flatpak application ID to the wrapper, so no need to create a symlink for the sandbox or a wrapper for the Vim Flatpak on the host.  
It should generate a test build in a couple of minutes.  
See #222

**Comment by tinywrkb** [comment]
And it looks like the Vim Flatpak is already bind-mounting `/tmp` from the host, so the filesystem override only needed for qutebrowser.  
Works fine here.

**Comment by tinywrkb** [comment]
Test build is ready if you want to try.

**Comment by tinywrkb** [comment]
Merged, and published early. The update should be in Flathub in a couple of minutes.

**Comment by tinywrkb** [comment]
Please let me know if I missed other common and important executables.

**Comment by jconnolly837** [comment]
Fantastic work! And quick too. 

On a fresh OpenSUSE 15.4 virtual machine, the only tweaking that needed to be done after installing all three apps was `--talk-name=org.fredesktop.Flatpak` and `--filesystem=/tmp:rw` to `org.qutebrowser.qutebrowser`. MPV and Gvim launched flawlessly from Qutebrowser. 

I do understand that those permissions shouldn't be shipped by default because they create a massive hole in the sandbox.
