### ISSUE TITLE
Include tldextract for userscripts

### ISSUE THREAD

**Issue by Aledosim** [flathub/org.qutebrowser.qutebrowser#34]
I'm trying to run qute-bitwarden, a userscript from qutebrowser, but it fails to find tldextract python module. Is there some way to include this module in this flatpak?

**Comment by tinywrkb** [comment]
Oh sorry, I haven't looked at all at Python userscripts. I'll go through them later today and add the missing modules.

**Comment by tinywrkb** [comment]
@Aledosim #35 should fix this issue. The buildbot should generate a test build soon for you to try.  
I'm not sure if clipboard backends of pyperclip are needed, if so then I try adding them tomorrow, it's a bit too late for today.

**Comment by tinywrkb** [comment]
Let's keep this open as it's not solved.

I added the requested module but I don't see how this can work as we're also missing the bitwarden-cli, keyutils, and it seems like also rofi is used by default.  
I'm keeping open until we have a proper solution that doesn't require allowing the sandbox run commands on the host. I'm really not fond of the idea of using flatpak-spawn here.  
Do we want to also add the missing packages? definitely not rofi, not sure about the first two.

**Comment by tinywrkb** [comment]
Closing in favor of #132.
