### ISSUE TITLE
Regression: MP3 and H.264 support missing even with ffmpeg-full runtime

### ISSUE THREAD

**Issue by tidux** [flathub/org.qutebrowser.qutebrowser#47]
Demo site for video: https://lab.html5test.com/codecs

Demo site for audio: http://r-a-d.io/ 

System details: Ubuntu 18.04 amd64, Flatpak 1.0.9, latest Qutebrowser+ffmpeg packages installed from Flathub.

**Comment by tinywrkb** [comment]
> Demo site for audio: http://r-a-d.io/

Working for me. I can even play the mp3 stream directly by opening this link in a new tab: `https://stream.r-a-d.io/main.mp3`.

> Demo site for video: https://lab.html5test.com/codecs

Doesn't even work in Edge or Chrome. The video examples in the following sites are playing correctly for me: https://tekeye.uk/html/html5-video-test-page and http://demo.nimius.net/video_test/.

Do you have the correct version of the FFMPEG extension installed?
```
$ flatpak info org.freedesktop.Platform.ffmpeg-full//20.08
```

**Comment by tidux** [comment]
I do have the correct version of the extension installed.  In troubleshooting further this appears to be a proxy related issue - I get full functionality when `content.proxy = system` but when using `content.proxy = socks://localhost:8080` with an `ssh -nND 8080 user@remote.host` tunnel, I get the above errors.

```
$ flatpak info org.freedesktop.Platform.ffmpeg-full//20.08
Ref: runtime/org.freedesktop.Platform.ffmpeg-full/x86_64/20.08
ID: org.freedesktop.Platform.ffmpeg-full
Arch: x86_64
Branch: 20.08
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2021-05-30 23:39:20 +0000
Subject: Export org.freedesktop.Platform.ffmpeg-full
Commit: 0f61f51f86c9e8375b9d3409e31b8212cb6dc708ac99d3037311901b80cb3ae3
Parent: d7f3c77ea01206f3f7f9597a33107bd9a31c0e5014db78e1ffe219a537295bd4
Location: /var/lib/flatpak/runtime/org.freedesktop.Platform.ffmpeg-full/x86_64/20.08/0f61f51f86c9e8375b9d3409e31b8212cb6dc708ac99d3037311901b80cb3ae3
Installed size: 10.6 MB
```

**Comment by tinywrkb** [comment]
Please try to [downgrade the app](https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#downgrading) and confirm that this is a regression and not something that is broken on your hand.  
Post the first commit that works for you.

**Comment by tidux** [comment]
It looks like it was a network firewall issue (unfortunately on an edge device I do not control) that was causing the problem.  Same socks5 proxy setup on a different local wifi network was able to connect.

**Comment by tinywrkb** [comment]
Alright, thanks for reporting back.
