### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by Evidlo** [flathub/org.qutebrowser.qutebrowser#51]
I get lots of "Server's certificate is not trusted." SSL errors on all pages.  I've checked that my SSL certs are up to date, and run `update-ca-certificates` to be sure.

I also considered that it might be a flatpak filesystem permissions issue, which I run into quite often, but I'm able to open `file:///etc/ssl/certs` just fine.

This is on Debian testing.

<details><summary>version info</summary><pre>
Version info
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.2.3
Git commit: f35f56e-dirty on HEAD (2021-06-01 18:31:44 +0200)
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.3

CPython: 3.8.8
PyQt: 5.15.4

sip: 4.19.25
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.4.1
adblock: 0.4.4
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: 2.8.335 (/app/share/pdf.js/build/pdf.js)
sqlite: 3.32.1
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: None
Platform: Linux-5.10.0-6-amd64-x86_64-with-glibc2.2.5, 64bit
Linux distribution: KDE Flatpak runtime (kde_flatpak)
Frozen: False
Imported from /app/lib/python3.8/site-packages/qutebrowser-2.2.3-py3.8.egg/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/libexec, data path: /usr

Paths:
cache: /home/evan/.var/app/org.qutebrowser.qutebrowser/cache/qutebrowser
config: /home/evan/.var/app/org.qutebrowser.qutebrowser/config/qutebrowser
data: /home/evan/.var/app/org.qutebrowser.qutebrowser/data/qutebrowser
runtime: /run/user/1000/app/org.qutebrowser.qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 5:39:14
Yank pastebin URL for version info
Copyright info
Copyright 2014-2021 Florian Bruhin (The Compiler)

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/ or open qute://gpl.
</pre></details>

<details><summary>openssl output</summary><pre>
[evan@blackbox ~] openssl s_client -connect www.python.org:443
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Extended Validation Serve
r CA
verify return:1
depth=0 businessCategory = Private Organization, jurisdictionC = US, jurisdictionST = Delaware, seria
lNumber = 3359300, C = US, ST = Oregon, L = Beaverton, O = Python Software Foundation, CN = www.pytho
n.org
verify return:1
---
Certificate chain
 0 s:businessCategory = Private Organization, jurisdictionC = US, jurisdictionST = Delaware, serialNu
mber = 3359300, C = US, ST = Oregon, L = Beaverton, O = Python Software Foundation, CN = www.python.o
rg
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Extended Validation Server C
A
 1 s:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Extended Validation Server C
A
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIIBDCCBuygAwIBAgIQCgvu6rKU/G36blVsu5S6BzANBgkqhkiG9w0BAQsFADB1
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMTQwMgYDVQQDEytEaWdpQ2VydCBTSEEyIEV4dGVuZGVk
IFZhbGlkYXRpb24gU2VydmVyIENBMB4XDTIwMDkyOTAwMDAwMFoXDTIxMTAzMTAw
MDAwMFowgdExHTAbBgNVBA8MFFByaXZhdGUgT3JnYW5pemF0aW9uMRMwEQYLKwYB
BAGCNzwCAQMTAlVTMRkwFwYLKwYBBAGCNzwCAQITCERlbGF3YXJlMRAwDgYDVQQF
EwczMzU5MzAwMQswCQYDVQQGEwJVUzEPMA0GA1UECBMGT3JlZ29uMRIwEAYDVQQH
EwlCZWF2ZXJ0b24xIzAhBgNVBAoTGlB5dGhvbiBTb2Z0d2FyZSBGb3VuZGF0aW9u
MRcwFQYDVQQDEw53d3cucHl0aG9uLm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAKb7uzSV2u41/YZbs+vvB5ob5BVQtKYKg+npgFfdvn/yMuG5Vrvl
iokKJL3RtQGQDGZmYkhsUah2yiYCsQ0dzjBUquG1yxzprRkn1/m/dtwDjH8+mm+t
my80sSVp3TVCnnDuuzazxe0HBGcRM8yqnW5aN+AXV074UUuRRx0ixZy3ttoHl66M
MshcFdJ1mKOKm1ZKCque4Ydk1EizWSjiDtIj4wRzHbOjuGtZrbv+uw396ILmI6oI
AcKIC7VkteEe2s04cXOh7inQgw+fMeiVEnLs+TADNAvYG+4zYNk1ddL3QxiqYTld
JyyUAdIdE5+Q1U2kJrVQnCvAWCAMFVElBzkCAwEAAaOCBDEwggQtMB8GA1UdIwQY
MBaAFD3TUKXWoK3u80pgCmXTIdT4+NYPMB0GA1UdDgQWBBREsu1+8w+FHnZxpf7i
oOhf7b0BVjCCAVQGA1UdEQSCAUswggFHgg53d3cucHl0aG9uLm9yZ4IPZG9jcy5w
eXRob24ub3Jngg9idWdzLnB5dGhvbi5vcmeCD3dpa2kucHl0aG9uLm9yZ4INaGcu
cHl0aG9uLm9yZ4IPbWFpbC5weXRob24ub3Jngg9weXBpLnB5dGhvbi5vcmeCFHBh
Y2thZ2luZy5weXRob24ub3JnghBsb2dpbi5weXRob24ub3Jnggx1cy5weWNvbi5v
cmeCCHB5cGkub3JnggdweXBpLmlvggxkb2NzLnB5cGkuaW+CDWRvY3MucHlwaS5v
cmeCDmRvbmF0ZS5weXBpLmlvgg9kb25hdGUucHlwaS5vcmeCE2Rldmd1aWRlLnB5
dGhvbi5vcmeCE3d3dy5idWdzLnB5dGhvbi5vcmeCCnB5dGhvbi5vcmeCFGRvd25s
b2Fkcy5weXRob24ub3JnMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF
BQcDAQYIKwYBBQUHAwIwdQYDVR0fBG4wbDA0oDKgMIYuaHR0cDovL2NybDMuZGln
aWNlcnQuY29tL3NoYTItZXYtc2VydmVyLWczLmNybDA0oDKgMIYuaHR0cDovL2Ny
bDQuZGlnaWNlcnQuY29tL3NoYTItZXYtc2VydmVyLWczLmNybDBLBgNVHSAERDBC
MDcGCWCGSAGG/WwCATAqMCgGCCsGAQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2Vy
dC5jb20vQ1BTMAcGBWeBDAEBMIGIBggrBgEFBQcBAQR8MHowJAYIKwYBBQUHMAGG
GGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBSBggrBgEFBQcwAoZGaHR0cDovL2Nh
Y2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0U0hBMkV4dGVuZGVkVmFsaWRhdGlv
blNlcnZlckNBLmNydDAMBgNVHRMBAf8EAjAAMIIBBQYKKwYBBAHWeQIEAgSB9gSB
8wDxAHcA9lyUL9F3MCIUVBgIMJRWjuNNExkzv98MLyALzE7xZOMAAAF02oPpyAAA
BAMASDBGAiEArg/ruTBvWubivrxwRytv8VGCpA3yVHTaKFiObDBcHrcCIQCFzUvP
ib7qJGqbLP5IWY11D6sxJvv/ZvIopE0SZW6CrAB2AFzcQ5L+5qtFRLFemtRW5hA3
+9X6R9yhc5SyXub2xw7KAAABdNqD6hoAAAQDAEcwRQIhAMgXNU82IlkTHbOUc/7L
ToliVL6Jin00+mc1isj0q6wiAiBsVKEdXbfCsLJZGb74Lkx1axdiMtDZWVSUJdTJ
7DtzJTANBgkqhkiG9w0BAQsFAAOCAQEAW84GOYCg3n2dfoKtNl1s20kkvbItnvSr
ysmVrCjG+DfvW+Z71Z9m0sukZOY0Aweky+DgvHZUkbPgZBoJ5L915hC8uKlgbk6K
0TjM7aKZkbtj8x68s3lOC0BiFC05WQxV82AxJkx5wygfGmavS703TPrGDb3XXcho
8cg409X9vcWnfVLohO/RAwwlhh8sYC8o46lGgC2k6F2S7Okgqxwsj+RgJ0d777J8
x7VVGTruzaUz8laEcs4jnuPrGw6OWT2v7YiEq3bIlz5hbYa/c6AGvJ44QUr+uEFW
okZVHOUC/rI3HN8rsApSNQRIVH6VCs1Zbz298lDhoBELMapBQEl9RA==
-----END CERTIFICATE-----
subject=businessCategory = Private Organization, jurisdictionC = US, jurisdictionST = Delaware, seria
lNumber = 3359300, C = US, ST = Oregon, L = Beaverton, O = Python Software Foundation, CN = www.pytho
n.org

issuer=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Extended Validation Server
 CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3831 bytes and written 386 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: FE937978DBF6FAC4A371689855ECEA09EAB0405A09E448C9CF81831E1D6D971F
    Session-ID-ctx:
    Resumption PSK: 6F7A76149F2664C54836153E69B7B45DB1F20383BEFE0137DB53E32AFE4652A56C27764B0803EBE05
1D1ACD67C87A956
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 604800 (seconds)
    TLS session ticket:
    0000 - f6 97 41 37 de 01 cf 20-10 d5 34 f8 af fd f9 91   ..A7... ..4.....
    0010 - fb 05 f6 fd 77 8b 16 49-61 55 87 17 b8 0a d6 13   ....w..IaU......
    0020 - 5a a8 0a 70 0b a6 0f 5b-19 0f d6 55 9f e2 e3 6e   Z..p...[...U...n
    0030 - ec 57 ca f6 15 a1 a3 d0-22 20 5c a1 b2 0d e1 f4   .W......" \.....
    0040 - a4 6a 1c ea 3d 17 82 36-cd 5d af f8 47 8d 95 23   .j..=..6.]..G..#
    0050 - a5 19 13 e8 89 ab e1 08-19 b1 28 2c 6f 7b 84 fc   ..........(,o{..
    0060 - 6e 32 b6 ed ff 2f 56 5e-09 c7 91 17 e6 c1 70 71   n2.../V^......pq
    0070 - f5 0b 0a 5f 24 7c a6 4f-9f 02 ff 1c 38 22 05 26   ..._$|.O....8".&
    0080 - 87 87 fb 6d 4e 1b 87 c7-89 3b af 1a 1d c8 c4 3b   ...mN....;.....;
    0090 - 5f 7a 6e 45 b1 c0 f7 df-d7 bd 13 3d e9 c8 eb e4   _znE.......=....

    Start Time: 1624483288
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
^C
[evan@blackbox ~]
</pre>
</summary>

**Comment by tinywrkb** [comment]
I can't say I understand much about these SSL issues.  

> I get lots of "Server's certificate is not trusted." SSL errors on all pages.

What do you mean by all pages? it that every site you visit? like the python.org?  
If so then I can't replicate.   
You'll have to give a more reproducible example.

There was a [bug a while back due to an update of the host installed p11-kit](https://github.com/flatpak/flatpak/issues/2921) so maybe this can a similar regression and distro specific one. If Debian Testing is packaging a non stable releases or heavily patch them then it's not a good candidate for testing the app.  
Please try with another distro. It's shouldn't take much more than a few minutes to spin a Fedora Silverblue VM and install the app.

Do you have a non standard Flatpak installation location (see man `flatpak-installation`) that you installed the runtime into with `flatpak install --installation=...`? if so then by default it has higher priority then the user or system Flatpak installations, and I don't think it's being checked for updates when running `flatpak update`.

You can check the Flatpak runtime that is being used and its installation location by running `$ flatpak run --command=cat org.qutebrowser.qutebrowser /.flatpak-info`.  
You can check that you're running the latest revision of the runtime by comparing commit SHAs with the locally installed runtime that being used by the app and the Flathub repo like this:

```
$ flatpak run --command=cat org.qutebrowser.qutebrowser /.flatpak-info | grep runtime-commit

runtime-commit=212d267860a3001081816007b074dd57993335aec23485c082d40034c6a5b857


$ flatpak remote-info --log flathub org.kde.Platform//5.15 | less

        ID: org.kde.Platform
       Ref: runtime/org.kde.Platform/x86_64/5.15
      Arch: x86_64
    Branch: 5.15
Collection: org.flathub.Stable
  Download: 368.5 MB
 Installed: 1.0 GB

    Commit: 212d267860a3001081816007b074dd57993335aec23485c082d40034c6a5b857
    Parent: 8f64abe539706bfa5173ef22f72215456b0c96ad0e540103ad1833c6a726fe66
   Subject: build of org.kde.Sdk, Thu 17 Jun 2021 01:07:39 PM UTC (fe4751105dd9e14b97d195c9e4e19d5dbefd2aae)
      Date: 2021-06-17 19:38:25 +0000
   History:
....
```

> I've checked that my SSL certs are up to date, and run update-ca-certificates to be sure.

If I understand it correctly, Flatpak is using the host installed certificates if you have p11-kit-server running for your user. if p11-kit-server is not running, the app will use the certificates that the runtime supplies. The relevant code was introduced [here](https://github.com/flatpak/flatpak/commit/66b2ff40f7caf3a731814cbb7670e8d91c732e95).  
On my system, I have the socket systemd unit enabled by the service don't seem to be running so I guess host certificates are not being used.  
With systemd, you can check if the p11-kit-server service is running like this

```
$ systemctl status --user p11-kit-server.service
```

If you will start the service and then open the app, the host certificates should be used.  
Test in both scenarios, when the service is running and when it's not.  
Also try starting and stopping the socket unit.


qutebrowser seems to require too much user interaction and input when it encounter certificates that should be blocked by default. Open `https://badssl.com/dashboard/` in qutebrowser and compare to another Chromium based browser.  
Maybe this a non Flatpak related issue.

> openssl s_client -connect www.python.org:443  ...

You can run also in the Flatpak sandbox and compare the result.

```
$ flatpak run --command=openssl org.qutebrowser.qutebrowser s_client -connect www.python.org:443
```

> Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122

You're not running the latest version of the app. The recent update is on QtWebEngine 5.15.5 and Chromium 87.

**Comment by The-Compiler** [comment]
> qutebrowser seems to require too much user interaction and input when it encounter certificates that should be blocked by default. Open https://badssl.com/dashboard/ in qutebrowser and compare to another Chromium based browser. Maybe this a non Flatpak related issue.

That's by design. Other browsers silently block requests to subresources, qutebrowser instead tells the user that something is wrong. Since v2.2.0, you can set `content.tls.certificate_errors` to `ask-block-thirdparty` to automatically block those (like the dialog explains :wink:).

**Comment by tinywrkb** [comment]
@Evidlo is this still an issue? Did you confirm that this behavior diverges from non-Flatpak qutebrowser?

**Comment by Evidlo** [comment]
Sorry for the late response.  I've just reinstalled the flatpak and it seems to be working normally.
