### ISSUE TITLE
File picking dialog no longer works

### ISSUE THREAD

**Issue by alandiwix** [flathub/org.qutebrowser.qutebrowser#97]
Nothing happens when I push any "choose file" button.
Issue appeared approximately a month ago (with several other issues) - I could pick files just fine before that.

**Comment by tinywrkb** [comment]
I can't reproduce. It works for me in a reasonably updated Arch Linux system with the GTK portal, and in Kinoite 35 with the KDE portal.  
Tested [ShareDrop](https://www.sharedrop.io/), and [this test page](https://viljamis.com/filetest/).

**Comment by alandiwix** [comment]
@tinywrkb thanks for the answer. I don't have a portal, but why it was working perfectly fine without one before?

**Comment by tinywrkb** [comment]
Are you sure you're using the Flatpak app? Flatpak requires a XDG desktop portals implementation. I find it hard to believe that your allows you to install Flatpak without pulling in a XDG portals impl.

**Comment by alandiwix** [comment]
@tinywrkb
No, I have neither xdg-desktop-portal package nor any specific implementation like xdg-desktop-portal-gtk or xdg-desktop-portal-kde.
Never had.

**Comment by tinywrkb** [comment]
> Yes, I'm sure that I'm using flatpak, but no, I have neither xdg-desktop-portal package nor any specific implementation like xdg-desktop-portal-gtk or xdg-desktop-portal-kde.
Never had. Flatpak never required those, it always used built-in file picker (GTK apps still do).

If there's no hard dependency of the distro Flatpak package on and XDG portals impl, then the Flatpak package maintainer of your distro is at fault.  
Flatpak requires a XDG desktop portals implementation, and other things can break, not only the file picker.  
This should be reported as a packaging issue in your distro bug tracking system.  
I'm sure other Flathub app maintainers would appreciate not having to deal with bug created by wrong distro packaging decisions.  
Which distro are you using?

**Comment by alandiwix** [comment]
@tinywrkb Would you kindly provide a documentation entry that enforces using `xdg-desktop-portal` in this case (so I could provide a proof to the distribution package mainainer)?

**Comment by tinywrkb** [comment]
@alandiwix [This](https://github.com/flatpak/flatpak/wiki/Distribution#other-things-to-package) is the best I can find.  
I will opened a bug report requesting to make it clear that portal implementation are mandatory dependency, as it's unacceptable for a Flathub app maintainer to deal with bad distro packaging decisions.  
And this is a bad packaging decision, because this is a major feature of Flatpak.  

You didn't say which distro you're using.

**Comment by alandiwix** [comment]
@tinywrkb This is clear that portals are used by *some applications*, *not flatpak itself*, so I would avoid adding it as hard dependency. Thanks for the help.
